<?php

namespace Troiswa\BackBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActeursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActeursRepository extends EntityRepository
{
    public function getNombreActeur()
    {
        $query=$this->getEntityManager()->createQuery(
            "SELECT count(a) FROM TroiswaBackBundle:Acteurs a"
        );
        return $query->getSingleScalarResult();
    }
    public function getNbGenreActeur()
    {
        $query=$this->getEntityManager()->createQuery(
            "SELECT count(a.id) FROM TroiswaBackBundle:Acteurs a
            group by a.sexe"
        );
        return $query->getResult();
    }
    public function getAllHommes()
    {
        $query=$this->getEntityManager()->createQuery(
            "SELECT a FROM TroiswaBackBundle:Acteurs a
            WHERE a.sexe=0"
        );
        return $query->getResult();
    }  
    public function getAllFemmes()
    {
        $query=$this->getEntityManager()->createQuery(
            "SELECT a FROM TroiswaBackBundle:Acteurs a
            WHERE a.sexe=1"
        );
        return $query->getResult();
    }        
}

