<?php

namespace Troiswa\BackBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FilmsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilmsRepository extends EntityRepository
{
    public function getNombreDeFilm()
    {
        $query=$this->getEntityManager()->createQuery(
          "SELECT count(f) FROM TroiswaBackBundle:Films f"
          /*'f' correspond à l'alias de la table. On peut la renommer comme on veut.*/
        );
        /*die(var_dump($query->getSingleScalarResult()));*/
        return $query->getSingleScalarResult();
    }
    public function getBestFilm()
    {
        $query=$this->getEntityManager()->createQuery(
            "SELECT f FROM TroiswaBackBundle:Films f
            ORDER BY f.note DESC"
        );
        //die(var_dump($query->setMaxResults(1)->getSingleResult()));//
        return $query->setMaxResults(1)->getSingleResult();
    }
    public function getLastFilm($nb)
    {
        $query=$this->getEntityManager()->createQuery(
            "SELECT f FROM TroiswaBackBundle:Films f
            ORDER BY f.dateReal DESC"
        );
        //die(var_dump($query->setMaxResults(1)->getSingleResult()));//
        return $query->setMaxResults($nb)->getResult();
    }
    public function getFilmByGenre($type)
    {
        $query=$this->getEntityManager()->createQuery(
            "SELECT f FROM TroiswaBackBundle:Films f
            JOIN f.liaisonGenre g
            WHERE g.type=:letype"
        );
        return $query->setParameter("letype", $type)->getResult();
    }

}